<?php
require "list.php";

function get_cache_time()
{
    // try open, if not exist, create
    $file = fopen("time.pid", "a+");
    if (filesize("time.pid") == 0) {
        fwrite($file, 0);
        $time_last = 0;
    } else {
        $time_last = fread($file, filesize("time.pid"));
    }

    $time_now = time();
    fclose($file);
    return $time_now - $time_last;
}

function update_time()
{
    $file = fopen("time.pid", "w+");
    fwrite($file, time());
    fclose($file);
}

function update_content($content)
{
    $file = fopen("dns.cache", "w+");
    fwrite($file, $content);
    fclose($file);
}

function update_cache($content)
{
    update_content($content);
    update_time();
}

function render(): string
{
    global $domain_list;

    $ret = "#<pre>\n";
    $ret .= "####### Onenote Hosts Start #######" . "\n";
    $ret .= "# This file is generated by https://github.com/Zxilly/OnedriveHostsGenerator" . "\n";
    $ret .= "# Generate time: " . date("Y-m-d H:i:s") . "\n";

    foreach ($domain_list as $domain) {
        $dns = dns_get_record($domain, DNS_A);

        if (!$dns) {
            $ret .= "# " . $domain . " is not resolved" . "\n";
            continue;
        }

        $ips = array_map(function ($ip) {
            return $ip['ip'];
        }, $dns);

        $ips = array_unique($ips);

        foreach ($ips as $ip) {
            $pad_ip = str_pad($ip, 15);
            $ret .= $pad_ip . " " . $domain . "\n";
        }
    }

    $ret .= "####### Onenote Hosts End #######</pre>" . "\n";
    $ret .= "# <style>body{visibility: hidden}pre{visibility: visible;position:absolute;top:0}</style>" . "\n";

    return $ret;
}

function read_dns_cache(): string
{
    $file = fopen("dns.cache", "r+");
    $content = fread($file, filesize("dns.cache"));
    fclose($file);
    return $content;
}

function handle()
{
    $is_cache_invalid = get_cache_time() > 60000;
    $is_fresh = isset($_GET['fresh']);

    if ($is_fresh or $is_cache_invalid) {
        $content = render();

        if ($is_cache_invalid) {
            update_cache($content);
        }
    } else {
        $content = read_dns_cache();
    }
    echo $content;
}

handle();
